# Generated by Django 6.0.5 on 2026-05-31 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CauLacBo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_clb', models.CharField(max_length=100)),
                ('mo_ta', models.TextField()),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='clb/')),
            ],
        ),
        migrations.CreateModel(
            name='SuKien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_su_kien', models.CharField(max_length=200)),
                ('ngay_to_chuc', models.DateField()),
                ('dia_diem', models.CharField(max_length=200)),
                ('mo_ta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HoSoSinhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100)),
                ('mssv', models.CharField(max_length=20)),
                ('lop', models.CharField(max_length=50)),
                ('khoa', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('ngay_sinh', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DangKyCLB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_dang_ky', models.DateTimeField(auto_now_add=True)),
                ('trang_thai', models.CharField(default='Chờ duyệt', max_length=20)),
                ('clb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.caulacbo')),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.hososinhvien')),
            ],
        ),
        migrations.CreateModel(
            name='ThanhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100)),
                ('mssv', models.CharField(max_length=20)),
                ('lop', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('clb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.caulacbo')),
            ],
        ),
    ]
