# Generated by Django 6.0.5 on 2026-05-31 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DangKySuKien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_dang_ky', models.DateTimeField(auto_now_add=True)),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.hososinhvien')),
                ('su_kien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.sukien')),
            ],
        ),
    ]
