# Generated by Django 6.0.5 on 2026-06-07 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_dangkysukien'),
    ]

    operations = [
        migrations.AddField(
            model_name='dangkysukien',
            name='trang_thai',
            field=models.CharField(default='Chờ duyệt', max_length=20),
        ),
        migrations.CreateModel(
            name='FileThanhVienSuKien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_excel', models.FileField(upload_to='excel/')),
                ('ngay_upload', models.DateTimeField(auto_now_add=True)),
                ('su_kien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.sukien')),
            ],
        ),
    ]
