# Generated by Django 6.0.5 on 2026-06-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_dangkysukien_trang_thai_filethanhviensukien'),
    ]

    operations = [
        migrations.AddField(
            model_name='hososinhvien',
            name='vai_tro',
            field=models.CharField(default='SinhVien', max_length=20),
        ),
    ]
