# Generated by Django 6.0.5 on 2026-06-08 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_hososinhvien_vai_tro'),
    ]

    operations = [
        migrations.AddField(
            model_name='hososinhvien',
            name='clb_quan_ly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quan_tri_vien', to='club.caulacbo'),
        ),
    ]
