# Generated by Django 6.0.5 on 2026-06-13 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_hososinhvien_clb_quan_ly'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        
        migrations.CreateModel(
            name='TaiLieuCLB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_file', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='tailieu/')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('clb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.caulacbo')),
            ],
        ),
        migrations.CreateModel(
            name='ThongBaoCLB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=200)),
                ('noi_dung', models.TextField()),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('clb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.caulacbo')),
            ],
        ),
        migrations.CreateModel(
            name='TinNhanCLB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('ngay_gui', models.DateTimeField(auto_now_add=True)),
                ('clb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.caulacbo')),
                ('nguoi_gui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
