# Generated by Django 6.0.5 on 2026-06-13 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_caulacbo_gioi_thieu_hososinhvien_clb_tailieuclb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caulacbo',
            name='gioi_thieu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hososinhvien',
            name='clb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.caulacbo'),
        ),
    ]
