# Generated by Django 6.0.5 on 2026-06-15 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_caulacbo_gioi_thieu_hososinhvien_clb'),
    ]

    operations = [
        migrations.AddField(
            model_name='sukien',
            name='clb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.caulacbo'),
        ),
    ]
